# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [2]:
import numpy as np


#### 2. Print the numpy version and the configuration 

In [3]:
import numpy as np

# Print NumPy version
print("NumPy Version:", np.__version__)

# Print NumPy configuration
np.show_config()


NumPy Version: 2.1.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30154",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.27",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-0n6rph84/cp310-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/includ

c:\Python310\lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


#### 3. Create a null vector of size 10

In [4]:
import numpy as np

# Create a null vector of size 10
null_vector = np.zeros(10)

print(null_vector)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [5]:
import numpy as np

# Create an array (example array)
array = np.zeros(10)

# Find the memory size of the array
memory_size = array.nbytes

print(f"Memory size of the array: {memory_size} bytes")


Memory size of the array: 80 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [6]:
import numpy as np

# Get the documentation for the np.add function
help(np.add)



Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\python310\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be 

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [7]:
import numpy as np

# Create a null vector of size 10
null_vector = np.zeros(10)

# Set the fifth value (index 4) to 1
null_vector[4] = 1

print(null_vector)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [8]:
import numpy as np

# Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)

print(vector)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [9]:
import numpy as np

# Example vector
vector = np.arange(10, 50)

# Reverse the vector
reversed_vector = vector[::-1]

print(reversed_vector)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [10]:
import numpy as np

# Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)

print(matrix)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [11]:
import numpy as np

# Define the array
array = np.array([1, 2, 0, 0, 4, 0])

# Find indices of non-zero elements
non_zero_indices = np.nonzero(array)

print(non_zero_indices)


(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix

In [12]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

# Alternatively, you can use:
# identity_matrix = np.identity(3)

print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [13]:
import numpy as np

# Create a 3x3x3 array with random values
random_array = np.random.random((3, 3, 3))

print(random_array)


[[[0.96469423 0.48585608 0.16730974]
  [0.66047417 0.26225663 0.53704913]
  [0.85405862 0.55036783 0.81289302]]

 [[0.64127066 0.25400001 0.7379359 ]
  [0.47200465 0.621493   0.14768782]
  [0.35636884 0.34113205 0.7089544 ]]

 [[0.81684499 0.66639425 0.26260126]
  [0.42511338 0.67162218 0.47411073]
  [0.93286385 0.28077708 0.31814091]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [14]:
import numpy as np

# Create a 10x10 array with random values
random_array = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random Array:")
print(random_array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)


Random Array:
[[0.73751173 0.46924594 0.95683973 0.97223275 0.05970322 0.03720203
  0.91155665 0.83521855 0.89400224 0.48922484]
 [0.92003179 0.01469027 0.46785894 0.69568747 0.27340978 0.8938656
  0.14507951 0.02997276 0.44704349 0.77007955]
 [0.16238973 0.35323028 0.06071753 0.66856374 0.05550693 0.51309899
  0.66927347 0.79582576 0.24052188 0.09483751]
 [0.18168154 0.37841342 0.5348925  0.4114838  0.88711646 0.98813814
  0.18454831 0.29522476 0.90684414 0.13185765]
 [0.57066872 0.73955477 0.08310391 0.2043143  0.6986303  0.63703493
  0.80883215 0.98170512 0.8347008  0.74988489]
 [0.12637425 0.64484612 0.18144849 0.68980224 0.72740364 0.2980261
  0.719428   0.81409239 0.3217839  0.861791  ]
 [0.5685062  0.27216397 0.19539561 0.57069711 0.08810248 0.89061016
  0.71892957 0.12003016 0.48903062 0.24812266]
 [0.84273103 0.79492767 0.75096566 0.72627065 0.24424951 0.15347883
  0.70569469 0.16778626 0.55436212 0.53701468]
 [0.90283905 0.78257817 0.96139505 0.61941624 0.59022308 0.66493907


#### 14. Create a random vector of size 30 and find the mean value

In [17]:
import numpy as np

# Create a random vector of size 30
random_vector = np.random.random(30)

# Find the mean value
mean_value = np.mean(random_vector)

print("Random Vector:")
print(random_vector)
print("Mean value:", mean_value)


Random Vector:
[0.28892826 0.25096119 0.91288331 0.26833992 0.09970664 0.95719548
 0.68438992 0.9955591  0.43746143 0.35700816 0.39292185 0.25564775
 0.34561929 0.68838554 0.32403308 0.30115661 0.33428614 0.96304109
 0.45116656 0.40054986 0.48594614 0.24299671 0.28276593 0.8065895
 0.65104458 0.15913637 0.06324603 0.77690735 0.58716482 0.45199368]
Mean value: 0.47390107754525634


#### 15. Create a 2d array with 1 on the border and 0 inside

In [18]:
import numpy as np

# Define the size of the 2D array
size = 5  # You can change this to any size

# Create a 2D array filled with zeros
array = np.zeros((size, size), dtype=int)

# Set the border to 1
array[0, :] = 1      # Top border
array[-1, :] = 1     # Bottom border
array[:, 0] = 1      # Left border
array[:, -1] = 1     # Right border

print(array)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [19]:
import numpy as np

# Create an example array
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Add a border filled with 0s
bordered_array = np.pad(array, pad_width=1, mode='constant', constant_values=0)

print("Original Array:")
print(array)
print("\nArray with Border:")
print(bordered_array)


Original Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with Border:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan → nan
np.nan == np.nan → False
np.inf > np.nan → False
np.nan - np.nan → nan
np.nan in set([np.nan]) → True
0.3 == 3 * 0.1 → False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [21]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Set values just below the diagonal
values = [1, 2, 3, 4]  # Values to place just below the diagonal
np.fill_diagonal(matrix[1:], values)

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [22]:
import numpy as np

# Create an 8x8 matrix
checkerboard = np.zeros((8, 8))

# Fill the checkerboard pattern
checkerboard[1::2, ::2] = 1  # Fill 1s in even rows
checkerboard[::2, 1::2] = 1   # Fill 1s in odd rows

print(checkerboard)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
The index of the 100th element in a (6, 7, 8) shape array is:
(1, 5, 3)
